# Generated by Django 6.0.4 on 2026-09-07 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models



def snapshot_legacy_orders(apps, schema_editor):
    Orders = apps.get_model('orders', 'Orders')
    OrderItem = apps.get_model('orders', 'OrderItem')
    alias = schema_editor.connection.alias
    for order in Orders.objects.using(alias).select_related('product__seller__user', 'buyer__user').iterator():
        plan = order.product
        seller = plan.seller
        order.reference = uuid.uuid4()
        order.is_legacy = True
        order.total = None
        order.guest_email = order.buyer.user.email if order.buyer_id else ''
        order.guest_phone = order.buyer.phone if order.buyer_id else ''
        # QuerySet.update preserves the original created_at and updated_at timestamps.
        Orders.objects.using(alias).filter(pk=order.pk).update(
            reference=order.reference, is_legacy=True, total=None,
            guest_email=order.guest_email, guest_phone=order.guest_phone,
        )
        OrderItem.objects.using(alias).create(
            order_id=order.pk, plan_id=plan.pk, seller_id=plan.seller_id,
            plan_id_snapshot=plan.pk, seller_id_snapshot=plan.seller_id,
            title_snapshot=plan.title,
            seller_name_snapshot=(seller.user.name or '') if seller else '',
            unit_price=None,
        )


def reverse_empty_database_only(apps, schema_editor):
    # Historical prices cannot be reconstructed. Never discard populated snapshots.
    from django.db.migrations.exceptions import IrreversibleError
    if apps.get_model('orders', 'Orders').objects.using(schema_editor.connection.alias).exists():
        raise IrreversibleError('Restore a backup to reverse populated order snapshots.')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_catalogue_plan_file'),
        ('orders', '0001_initial'),
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id_snapshot', models.PositiveBigIntegerField()),
                ('seller_id_snapshot', models.PositiveBigIntegerField(null=True)),
                ('title_snapshot', models.CharField(max_length=200)),
                ('seller_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(default='KES', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='orders',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='orders',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_legacy',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='reference',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.buyer'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.catalogue'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sellerprofile'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'plan_id_snapshot'), name='order_unique_plan'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gt', 0), _connector='OR'), name='order_item_positive_price'),
        ),
        migrations.RunPython(snapshot_legacy_orders, reverse_empty_database_only),
        migrations.AlterField(
            model_name='orders', name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'KES')), name='orders_currency_kes'),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_legacy', True), ('total__isnull', True)), models.Q(('total__gt', 0), ('total__isnull', False)), _connector='OR'), name='orders_valid_total'),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
