# Generated by Django 6.0.4 on 2026-09-07 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderitem_remove_orders_amount_remove_orders_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=21)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('initiating', 'Initiating'), ('pending', 'Awaiting payment confirmation'), ('rejected', 'Initiation rejected'), ('unknown', 'Needs reconciliation')], default='initiating', max_length=12)),
                ('merchant_request_id', models.CharField(blank=True, max_length=128)),
                ('checkout_request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='orders.orders')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'idempotency_key'), name='payment_order_idempotency'), models.UniqueConstraint(condition=models.Q(('status__in', ['initiating', 'pending', 'unknown'])), fields=('order',), name='payment_one_active_order'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive_amount')],
            },
        ),
    ]
