# Generated by Django 6.0.4 on 2026-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('merchant_request_id', models.CharField(max_length=128)),
                ('checkout_request_id', models.CharField(db_index=True, max_length=128)),
                ('result_code', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=21, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('receipt_number', models.CharField(blank=True, max_length=32)),
                ('transaction_date', models.CharField(blank=True, max_length=14)),
                ('status', models.CharField(default='received', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('verified_result_code', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(choices=[('initiating', 'Initiating'), ('pending', 'Awaiting payment confirmation'), ('rejected', 'Initiation rejected'), ('unknown', 'Needs reconciliation'), ('succeeded', 'Payment confirmed'), ('failed', 'Payment failed')], default='initiating', max_length=12),
        ),
    ]
