# Generated by Django 6.0.4 on 2026-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('designs', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
        ),
    ]
