# Generated by Django 6.0.4 on 2026-09-07 04:52

import catalogue.models
import catalogue.storage
import catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_catalogue_plan_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='plan_file',
            field=models.FileField(blank=True, null=True, storage=catalogue.storage.private_plan_storage, upload_to=catalogue.models.plan_file_upload_path, validators=[catalogue.validators.validate_plan_file]),
        ),
    ]
