# Generated by Django 6.0.4 on 2026-10-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_catalogue_plan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='floor_area_unit',
            field=models.CharField(choices=[('sqm', 'Square metres'), ('sqft', 'Square feet')], default='sqm', max_length=4),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='package_contents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='plot_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='storeys',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
