"""
Django settings for plan project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# The real environment file lives at backend/.env, outside the Django project
# directory. Loading it explicitly keeps management commands consistent no matter
# which directory they are run from.
if os.getenv('DJANGO_LOAD_DOTENV', 'True').lower() == 'true':
    load_dotenv(BASE_DIR.parent / '.env')


def get_list_environment_value(name):
    """Return a comma-separated environment variable as a clean list."""
    return [value.strip() for value in os.getenv(name, '').split(',') if value.strip()]


# M-Pesa configuration for django-daraja.
MPESA_ENVIRONMENT = os.getenv('DARAJA_ENVIRONMENT', 'sandbox')
MPESA_CONSUMER_KEY = os.getenv('DARAJA_CONSUMER')
MPESA_CONSUMER_SECRET = os.getenv('DARAJA_SECRET')
MPESA_PASSKEY = os.getenv('DARAJA_PASSKEY')
MPESA_SHORTCODE = os.getenv('DARAJA_SHORTCODE')
MPESA_EXPRESS_SHORTCODE = os.getenv('DARAJA_SHORTCODE')
PAYMENT_INITIATION_ENABLED = os.getenv('PAYMENT_INITIATION_ENABLED', 'False').lower() in {'1', 'true', 'yes', 'on'}
MPESA_CALLBACK_URL = os.getenv('MPESA_CALLBACK_URL', '')
MPESA_CONNECT_TIMEOUT = float(os.getenv('MPESA_CONNECT_TIMEOUT', '5'))
MPESA_READ_TIMEOUT = float(os.getenv('MPESA_READ_TIMEOUT', '20'))
CHECKOUT_TOKEN_MAX_AGE = 30 * 60
CHECKOUT_SESSION_MAX_AGE = int(os.getenv('CHECKOUT_SESSION_MAX_AGE', '86400'))
DOWNLOAD_TOKEN_MAX_AGE = int(os.getenv('DOWNLOAD_TOKEN_MAX_AGE', '600'))
CORS_ALLOW_HEADERS = (*default_headers, 'x-checkout-token', 'x-checkout-session', 'x-download-token')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError('SECRET_KEY must be configured in the environment.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = get_list_environment_value('ALLOWED_HOSTS')
CORS_ALLOWED_ORIGINS = get_list_environment_value('CORS_ALLOWED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'catalogue',
    'payments',
    'django_daraja',
    'orders',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

ROOT_URLCONF = 'plan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'plan_db'),
        'USER': os.getenv('DB_USER', 'plan'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files configuration (required for ImageFields)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
